//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 04:51:31 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ebi.ac.uk/biosamples/SampleGroupExport/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.ac.ebi.fgpt.webapp.v2.xml.samplegroupexport;
